---
title: "Commonality Analysis Code_2"
author: "Laura Jans and Arielle Smith"
date: "2025-08-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Loading Cleaned Data

```{r setup, echo=TRUE, message=FALSE, warning=FALSE}
# Use R 4.4.0

#Load required packages

library(groundhog)
groundhog_date <- "2025-04-10"
meta.groundhog(groundhog_date)

pkgs_analysis <- c("tidyverse", "yhat", "boot", "car", "lmtest", "olsrr", "psych",
                   "performance")
groundhog.library(pkgs_analysis, groundhog_date)

#Source custom functions
source("0_define_functions.R")

#Read in data from data cleaning and pre-processing code (to avoid re-running data prep every time)
cope_ca_data_nonimputed <- read.csv("cope_ca_data_nonimputed.csv")

set.seed(6804275)
```


# Creating Difference Scores

## Dependent Variable

```{r}
#Creating difference scores for depression (pre-SSI to 3M)
cope_ca_data_nonimputed <- cope_ca_data_nonimputed %>% 
  mutate(difference_score_cdi = f1_cdi_sum - b_cdi_sum)
```

## Independent Variables

```{r}
#Creating difference scores for hopelessness (pre-SSI to post-SSI) 
cope_ca_data_nonimputed <- cope_ca_data_nonimputed %>% 
  mutate(difference_score_bhs = pi_bhs_mean - b_bhs_mean)

#Creating difference scores for agency (pre-SSI to post-SSI) in both the imputed and non-imputed datasets 
cope_ca_data_nonimputed <- cope_ca_data_nonimputed %>% 
  mutate(difference_score_shs = pi_shs_mean - b_shs_mean)
```

# Running Full Regression Models (Nonimputed)

```{r, results = "asis", include=T, echo = T, message=FALSE, warning=FALSE}

# Subset data based on condition

cope_ca_data_nonimputed_PP <- subset(cope_ca_data_nonimputed, condition == 1)
cope_ca_data_nonimputed_ABC <- subset(cope_ca_data_nonimputed, condition == 2)

# Run full regression models

## Project Personality, Nonimputed

cdi_PP_nonimputed <- lm(difference_score_cdi ~ difference_score_bhs + difference_score_shs + pi_pfs_mean, data = cope_ca_data_nonimputed_PP)
summary(cdi_PP_nonimputed)

## ABC Project, Nonimputed

cdi_ABC_nonimputed <- lm(difference_score_cdi ~ difference_score_bhs + difference_score_shs + pi_pfs_mean, data = cope_ca_data_nonimputed_ABC)
summary(cdi_ABC_nonimputed)
```
Note: We decided to use mean for the PFS instead of component scores.

# Commonality Analysis (Nonimputed)

```{r, results = "asis", include=T, echo = T, message=FALSE, warning=FALSE}

# First, let's look at the r^2 for each full regression model

summary(cdi_PP_nonimputed)$r.squared
summary(cdi_ABC_nonimputed)$r.squared

# Decompose r^2 # Let's just try this once for the model predicting follow-up depression symptoms for Project Personality 

regOut_cdi_PP <- calc.yhat(cdi_PP_nonimputed, prec = 6)

# Bootstrap 1000 times to get CIs

set.seed(6804275)
if (!exists("boot.regOut_cdi_PP")) {
boot.regOut_cdi_PP <- boot(cope_ca_data_nonimputed_PP, boot.yhat.prec, 1000, lmOut = cdi_PP_nonimputed, regrout0 = regOut_cdi_PP, prec = 6)
}
boot.regOut_cdi_PP_result <- booteval.yhat(regOut_cdi_PP, boot.regOut_cdi_PP, bty="perc", prec = 6)
print(boot.regOut_cdi_PP_result$combCIaps) # Get commonality coefficients (and bootstrap CIs) for unique and common effects
print(boot.regOut_cdi_PP_result$combCIpm["b"]) # Get betas (and bootstrap CIs) for unique effects

# Define formulas for total effect models

bhs_formula <- difference_score_cdi ~ difference_score_bhs
shs_formula <- difference_score_cdi ~ difference_score_shs
pfs_formula <- difference_score_cdi ~ pi_pfs_mean

# Run custom function to bootstrap beta and R^2 for each total effect

bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_PP, beta_rsq, bhs_formula, 1000, 6)
bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_PP, beta_rsq, shs_formula, 1000, 6)
bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_PP, beta_rsq, pfs_formula, 1000, 6)

# Project ABC, Depression

regOut_cdi_ABC <- calc.yhat(cdi_ABC_nonimputed, prec = 6)

set.seed(6804275)
if (!exists("boot.regOut_cdi_ABC")) {
boot.regOut_cdi_ABC <- boot(cope_ca_data_nonimputed_ABC, boot.yhat.prec, 1000, lmOut = cdi_ABC_nonimputed, regrout0 = regOut_cdi_ABC, prec = 6)
}
boot.regOut_cdi_ABC_result <- booteval.yhat(regOut_cdi_ABC, boot.regOut_cdi_ABC, bty = "perc", prec = 6)
print(boot.regOut_cdi_ABC_result$combCIaps)
print(boot.regOut_cdi_ABC_result$combCIpm["b"])

#We use the same formulas as above

bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_ABC, beta_rsq, bhs_formula, 1000, 6)
bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_ABC, beta_rsq, shs_formula, 1000, 6)
bootstrap_beta_rsq(6804275, cope_ca_data_nonimputed_ABC, beta_rsq, pfs_formula, 1000, 6)
```

# Compute demographics

```{r}
# gender
count_perc_b_dem_gender_agender_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_agender")
count_perc_b_dem_gender_agender_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_agender")
count_perc_b_dem_gender_agender_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_agender")
count_perc_df_b_dem_gender_agender <- rbind(count_perc_b_dem_gender_agender_PP,
                       count_perc_b_dem_gender_agender_ABC,
                       count_perc_b_dem_gender_agender_total)
count_perc_df_b_dem_gender_agender 

count_perc_b_dem_gender_androgynous_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_androgynous")
count_perc_b_dem_gender_androgynous_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_androgynous")
count_perc_b_dem_gender_androgynous_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_androgynous")
count_perc_df_b_dem_gender_androgynous <- rbind(count_perc_b_dem_gender_androgynous_PP,
                       count_perc_b_dem_gender_androgynous_ABC,
                       count_perc_b_dem_gender_androgynous_total)
count_perc_df_b_dem_gender_androgynous 

count_perc_b_dem_gender_gender_expansive_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_gender_expansive")
count_perc_b_dem_gender_gender_expansive_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_gender_expansive")
count_perc_b_dem_gender_gender_expansive_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_gender_expansive")
count_perc_df_b_dem_gender_gender_expansive <- rbind(count_perc_b_dem_gender_gender_expansive_PP,
                       count_perc_b_dem_gender_gender_expansive_ABC,
                       count_perc_b_dem_gender_gender_expansive_total)
count_perc_df_b_dem_gender_gender_expansive 

count_perc_b_dem_gender_genderqueer_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_genderqueer")
count_perc_b_dem_gender_genderqueer_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_genderqueer")
count_perc_b_dem_gender_genderqueer_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_genderqueer")
count_perc_df_b_dem_gender_genderqueer <- rbind(count_perc_b_dem_gender_genderqueer_PP,
                       count_perc_b_dem_gender_genderqueer_ABC,
                       count_perc_b_dem_gender_genderqueer_total)
count_perc_df_b_dem_gender_genderqueer

count_perc_b_dem_gender_man_boy_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_man_boy")
count_perc_b_dem_gender_man_boy_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_man_boy")
count_perc_b_dem_gender_man_boy_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_man_boy")
count_perc_df_b_dem_gender_man_boy <- rbind(count_perc_b_dem_gender_man_boy_PP,
                       count_perc_b_dem_gender_man_boy_ABC,
                       count_perc_b_dem_gender_man_boy_total)
count_perc_df_b_dem_gender_man_boy

count_perc_b_dem_gender_nonbinary_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_nonbinary")
count_perc_b_dem_gender_nonbinary_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_nonbinary")
count_perc_b_dem_gender_nonbinary_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_nonbinary")
count_perc_df_b_dem_gender_nonbinary <- rbind(count_perc_b_dem_gender_nonbinary_PP,
                       count_perc_b_dem_gender_nonbinary_ABC,
                       count_perc_b_dem_gender_nonbinary_total)
count_perc_df_b_dem_gender_nonbinary

count_perc_b_dem_gender_not_sure_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_not_sure")
count_perc_b_dem_gender_not_sure_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_not_sure")
count_perc_b_dem_gender_not_sure_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_not_sure")
count_perc_df_b_dem_gender_not_sure <- rbind(count_perc_b_dem_gender_not_sure_PP,
                       count_perc_b_dem_gender_not_sure_ABC,
                       count_perc_b_dem_gender_not_sure_total)
count_perc_df_b_dem_gender_not_sure

count_perc_b_dem_gender_other_please_specify_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_other_please_specify")
count_perc_b_dem_gender_other_please_specify_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_other_please_specify")
count_perc_b_dem_gender_other_please_specify_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_other_please_specify")
count_perc_df_b_dem_gender_other_please_specify <- rbind(count_perc_b_dem_gender_other_please_specify_PP,
                       count_perc_b_dem_gender_other_please_specify_ABC,
                       count_perc_b_dem_gender_other_please_specify_total)
count_perc_df_b_dem_gender_other_please_specify

count_perc_b_dem_gender_third_gender_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_third_gender")
count_perc_b_dem_gender_third_gender_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_third_gender")
count_perc_b_dem_gender_third_gender_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_third_gender")
count_perc_df_b_dem_gender_third_gender <- rbind(count_perc_b_dem_gender_third_gender_PP,
                       count_perc_b_dem_gender_third_gender_ABC,
                       count_perc_b_dem_gender_third_gender_total)
count_perc_df_b_dem_gender_third_gender

count_perc_b_dem_gender_trans_female_trans_feminine_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_trans_female_trans_feminine")
count_perc_b_dem_gender_trans_female_trans_feminine_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_trans_female_trans_feminine")
count_perc_b_dem_gender_trans_female_trans_feminine_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_trans_female_trans_feminine")
count_perc_df_b_dem_gender_trans_female_trans_feminine <- rbind(count_perc_b_dem_gender_trans_female_trans_feminine_PP,
                       count_perc_b_dem_gender_trans_female_trans_feminine_ABC,
                       count_perc_b_dem_gender_trans_female_trans_feminine_total)
count_perc_df_b_dem_gender_trans_female_trans_feminine

count_perc_b_dem_gender_trans_male_trans_masculine_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_trans_male_trans_masculine")
count_perc_b_dem_gender_trans_male_trans_masculine_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_trans_male_trans_masculine")
count_perc_b_dem_gender_trans_male_trans_masculine_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_trans_male_trans_masculine")
count_perc_df_b_dem_gender_trans_male_trans_masculine <- rbind(count_perc_b_dem_gender_trans_male_trans_masculine_PP,
                       count_perc_b_dem_gender_trans_male_trans_masculine_ABC,
                       count_perc_b_dem_gender_trans_male_trans_masculine_total)
count_perc_df_b_dem_gender_trans_male_trans_masculine

count_perc_b_dem_gender_transgender_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_transgender")
count_perc_b_dem_gender_transgender_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_transgender")
count_perc_b_dem_gender_transgender_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_transgender")
count_perc_df_b_dem_gender_transgender <- rbind(count_perc_b_dem_gender_transgender_PP,
                       count_perc_b_dem_gender_transgender_ABC,
                       count_perc_b_dem_gender_transgender_total)
count_perc_df_b_dem_gender_transgender

count_perc_b_dem_gender_female_to_male_transgender_ftm_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_female_to_male_transgender_ftm")
count_perc_b_dem_gender_female_to_male_transgender_ftm_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_female_to_male_transgender_ftm")
count_perc_b_dem_gender_female_to_male_transgender_ftm_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_female_to_male_transgender_ftm")
count_perc_df_b_dem_gender_female_to_male_transgender_ftm <- rbind(count_perc_b_dem_gender_female_to_male_transgender_ftm_PP,
                       count_perc_b_dem_gender_female_to_male_transgender_ftm_ABC,
                       count_perc_b_dem_gender_female_to_male_transgender_ftm_total)
count_perc_df_b_dem_gender_female_to_male_transgender_ftm

count_perc_b_dem_gender_male_to_female_transgender_mtf_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_male_to_female_transgender_mtf")
count_perc_b_dem_gender_male_to_female_transgender_mtf_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_male_to_female_transgender_mtf")
count_perc_b_dem_gender_male_to_female_transgender_mtf_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_male_to_female_transgender_mtf")
count_perc_df_b_dem_gender_male_to_female_transgender_mtf <- rbind(count_perc_b_dem_gender_male_to_female_transgender_mtf_PP,
                       count_perc_b_dem_gender_male_to_female_transgender_mtf_ABC,
                       count_perc_b_dem_gender_male_to_female_transgender_mtf_total)
count_perc_df_b_dem_gender_male_to_female_transgender_mtf

count_perc_b_dem_gender_two_spirited_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_two_spirited")
count_perc_b_dem_gender_two_spirited_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_two_spirited")
count_perc_b_dem_gender_two_spirited_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_two_spirited")
count_perc_df_b_dem_gender_two_spirited <- rbind(count_perc_b_dem_gender_two_spirited_PP,
                       count_perc_b_dem_gender_two_spirited_ABC,
                       count_perc_b_dem_gender_two_spirited_total)
count_perc_df_b_dem_gender_two_spirited

count_perc_b_dem_gender_woman_girl_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_gender_woman_girl")
count_perc_b_dem_gender_woman_girl_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_gender_woman_girl")
count_perc_b_dem_gender_woman_girl_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_gender_woman_girl")
count_perc_df_b_dem_gender_woman_girl <- rbind(count_perc_b_dem_gender_woman_girl_PP,
                       count_perc_b_dem_gender_woman_girl_ABC,
                       count_perc_b_dem_gender_woman_girl_total)
count_perc_df_b_dem_gender_woman_girl

# race/ethnicity

count_perc_b_dem_race_american_indian_or_alaska_native_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_american_indian_or_alaska_native")
count_perc_b_dem_race_american_indian_or_alaska_native_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_american_indian_or_alaska_native")
count_perc_b_dem_race_american_indian_or_alaska_native_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_american_indian_or_alaska_native")
count_perc_df_b_dem_race_american_indian_or_alaska_native <- rbind(count_perc_b_dem_race_american_indian_or_alaska_native_PP,
                       count_perc_b_dem_race_american_indian_or_alaska_native_ABC,
                       count_perc_b_dem_race_american_indian_or_alaska_native_total)
count_perc_df_b_dem_race_american_indian_or_alaska_native

count_perc_b_dem_race_asian_including_asian_desi_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_asian_including_asian_desi")
count_perc_b_dem_race_asian_including_asian_desi_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_asian_including_asian_desi")
count_perc_b_dem_race_asian_including_asian_desi_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_asian_including_asian_desi")
count_perc_df_b_dem_race_asian_including_asian_desi <- rbind(count_perc_b_dem_race_asian_including_asian_desi_PP,
                       count_perc_b_dem_race_asian_including_asian_desi_ABC,
                       count_perc_b_dem_race_asian_including_asian_desi_total)
count_perc_df_b_dem_race_asian_including_asian_desi

count_perc_b_dem_race_black_african_american_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_black_african_american")
count_perc_b_dem_race_black_african_american_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_black_african_american")
count_perc_b_dem_race_black_african_american_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_black_african_american")
count_perc_df_b_dem_race_black_african_american <- rbind(count_perc_b_dem_race_black_african_american_PP,
                       count_perc_b_dem_race_black_african_american_ABC,
                       count_perc_b_dem_race_black_african_american_total)
count_perc_df_b_dem_race_black_african_american

count_perc_b_dem_race_hispanic_latinx_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_hispanic_latinx")
count_perc_b_dem_race_hispanic_latinx_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_hispanic_latinx")
count_perc_b_dem_race_hispanic_latinx_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_hispanic_latinx")
count_perc_df_b_dem_race_hispanic_latinx <- rbind(count_perc_b_dem_race_hispanic_latinx_PP,
                       count_perc_b_dem_race_hispanic_latinx_ABC,
                       count_perc_b_dem_race_hispanic_latinx_total)
count_perc_df_b_dem_race_hispanic_latinx

count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_native_hawaiian_or_other_pacific_islander")
count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_native_hawaiian_or_other_pacific_islander")
count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_native_hawaiian_or_other_pacific_islander")
count_perc_df_b_dem_race_native_hawaiian_or_other_pacific_islander <- rbind(count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_PP,
                       count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_ABC,
                       count_perc_b_dem_race_native_hawaiian_or_other_pacific_islander_total)
count_perc_df_b_dem_race_native_hawaiian_or_other_pacific_islander

count_perc_b_dem_race_other_specify_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_other_specify")
count_perc_b_dem_race_other_specify_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_other_specify")
count_perc_b_dem_race_other_specify_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_other_specify")
count_perc_df_b_dem_race_other_specify <- rbind(count_perc_b_dem_race_other_specify_PP,
                       count_perc_b_dem_race_other_specify_ABC,
                       count_perc_b_dem_race_other_specify_total)
count_perc_df_b_dem_race_other_specify

count_perc_b_dem_race_prefer_not_to_answer_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_prefer_not_to_answer")
count_perc_b_dem_race_prefer_not_to_answer_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_prefer_not_to_answer")
count_perc_b_dem_race_prefer_not_to_answer_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_prefer_not_to_answer")
count_perc_df_b_dem_race_prefer_not_to_answer <- rbind(count_perc_b_dem_race_prefer_not_to_answer_PP,
                       count_perc_b_dem_race_prefer_not_to_answer_ABC,
                       count_perc_b_dem_race_prefer_not_to_answer_total)
count_perc_df_b_dem_race_prefer_not_to_answer

count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_PP <- get_count_perc(cope_ca_data_nonimputed_PP,  "b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern")
count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_ABC <- get_count_perc(cope_ca_data_nonimputed_ABC, "b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern")
count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_total <- get_count_perc(cope_ca_data_nonimputed,     "b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern")
count_perc_df_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern <- rbind(count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_PP,
                       count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_ABC,
                       count_perc_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern_total)
count_perc_df_b_dem_race_white_caucasian_non_hispanic_includes_middle_eastern

# sexual orientation

cbind(Frequency = table(cope_ca_data_nonimputed_PP$b_dem_orientation), Percentage = round((prop.table(table(cope_ca_data_nonimputed_PP$b_dem_orientation))*100), 2))

cbind(Frequency = table(cope_ca_data_nonimputed_ABC$b_dem_orientation), Percentage = round((prop.table(table(cope_ca_data_nonimputed_ABC$b_dem_orientation))*100), 2))

cbind(Frequency = table(cope_ca_data_nonimputed$b_dem_orientation), Percentage = round((prop.table(table(cope_ca_data_nonimputed$b_dem_orientation))*100), 2))

# grade

cbind(Frequency = table(cope_ca_data_nonimputed_PP$b_dem_grade), Percentage = round((prop.table(table(cope_ca_data_nonimputed_PP$b_dem_grade))*100), 2))

cbind(Frequency = table(cope_ca_data_nonimputed_ABC$b_dem_grade), Percentage = round((prop.table(table(cope_ca_data_nonimputed_ABC$b_dem_grade))*100), 2))

cbind(Frequency = table(cope_ca_data_nonimputed$b_dem_grade), Percentage = round((prop.table(table(cope_ca_data_nonimputed$b_dem_grade))*100), 2))
```

# Multicollinearity

```{r results = "asis", include=T, echo = T, message=FALSE, warning=FALSE}
sqrt(vif(cdi_PP_nonimputed))
sqrt(vif(cdi_ABC_nonimputed))

# No perfect collinearity

# Estimating zero-order Pearson correlations among the predictors

print(
  psych::corr.test(
    cope_ca_data_nonimputed_PP[, c("difference_score_bhs", "difference_score_shs", "pi_pfs_mean")],
    use = "complete",
    method = "pearson"
  ),
  digits = 10
)

print(
  psych::corr.test(
    cope_ca_data_nonimputed_ABC[, c("difference_score_bhs", "difference_score_shs", "pi_pfs_mean")],
    use = "complete",
    method = "pearson"
  ),
  digits = 10
)
```

# Assumptions of full regression models (Nonimputed)

```{r, results = "asis", include=T, echo = T, message=FALSE, warning=FALSE}

# Linear relation of predictors with outcome
plot(cdi_PP_nonimputed, 1)
plot(cdi_ABC_nonimputed, 1)
#met for both models

# Independent errors
durbinWatsonTest(cdi_PP_nonimputed)  # rho_lag1 = -.126, D-W = 2.25, p = .008
durbinWatsonTest(cdi_ABC_nonimputed) # rho_lag1 =  .036, D-W = 1.93, p = .444
#met for both models except for cdi_PP_nonimputed

## Plot residuals for PP
res <- residuals(cdi_PP_nonimputed)

### Residuals vs. lagged residuals
current_res <- res[-1]
lagged_res  <- res[-length(res)]
plot(lagged_res, current_res,
     xlab = "Lagged Residuals (Previous Row)", ylab = "Residuals (Current Row)",
     main = "Residuals vs Lagged Residuals")
ar1_fit <- lm(current_res ~ lagged_res)
abline(ar1_fit, col = "red")
rho <- coef(ar1_fit)[2]
legend("topleft", bty = "n", text.col = "red",
       legend = paste0("rho_lag1 = ", round(rho, 3)))

### Residuals over data rows
plot_res_over_rows <- function(res, xlim = NULL) {
  title <- "Residuals Over Data Row Indices"
  if (!is.null(xlim)) title <- paste(title, paste0(xlim[1], "-", xlim[2]))
  
  plot(res, type = "o", main = title, xlim = xlim,
     xlab = "Row Index", ylab = "Residuals")
  abline(h = 0, col = "black", lwd = 2, lty = 2)
}

par(mfrow = c(3,1))
plot_res_over_rows(res)
plot_res_over_rows(res, c(100, 200))
plot_res_over_rows(res, c(200, 300))
par(mfrow = c(1,1))

## Rerun test for PP model fit to data with randomly sorted rows
cope_ca_data_nonimputed_PP_rand <- cope_ca_data_nonimputed_PP[sample(nrow(cope_ca_data_nonimputed_PP)), ]

cdi_PP_nonimputed_rand <- lm(formula(cdi_PP_nonimputed), cope_ca_data_nonimputed_PP_rand)
all.equal(summary(cdi_PP_nonimputed)$coefficients, 
          summary(cdi_PP_nonimputed_rand)$coefficients) # Same model summary

durbinWatsonTest(cdi_PP_nonimputed_rand) # rho_lag1 = .015, D-W = 1.96, p = .672 (no violation)

# Homoscedasticity
## plot
plot(cdi_PP_nonimputed, 3)
plot(cdi_ABC_nonimputed, 3)
## plot with CIs (per Shatz, 2024, p. 834)
plot(check_heteroscedasticity(cdi_PP_nonimputed))
plot(check_heteroscedasticity(cdi_ABC_nonimputed))
## original Breusch-Pagan test
ncvTest(cdi_PP_nonimputed)  # chisq(1) = 0.19, p = .663
ncvTest(cdi_ABC_nonimputed) # chisq(1) = 16.96, p < .001
#cdi_ABC_nonimputed did not meet assumption
## studentized Breusch-Pagan test
bptest(cdi_PP_nonimputed)   # BP = 4.53, df = 3, p = .210
bptest(cdi_ABC_nonimputed)  # BP = 15.39, df = 3, p = .002
#same outcome

# Normality of errors
ols_plot_resid_qq(cdi_PP_nonimputed)
ols_plot_resid_qq(cdi_ABC_nonimputed)

# We decided to use the Kolmogorov-Smirnov test to more formally examine normality 
# of errors based on the following recommendation: "The Shapiro–Wilk test is more 
# appropriate method for small sample sizes (<50 samples) although it can also be 
# handling on larger sample size while Kolmogorov–Smirnov test is used for n ≥50."
# (Mishra et al., 2019; https://doi.org/10.4103/aca.ACA_157_18 )

ols_test_normality(cdi_PP_nonimputed)
ols_test_normality(cdi_ABC_nonimputed)
#met for both models
```

```{r pull session info}
sink(file = "2025.08.25_sessionInfo_for_analysis_script.txt")
sessionInfo()
sink()
```
